sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.4.1

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose build
  - docker-compose run test

notifications:
  email: false
  hipchat:
    rooms:
      secure: JpswqIXnvSfUTHo6IEuTygGlYj4okzeYJAoNAAd+REayScJFRf7YquS4rb/qjsCmfoiJ6SfqxB87zbiQMT/5XfuaNZf8n8qG/+Ayd+AGzGamCMMjvB86BvZG7nrBSPZ4vgcfnjdOuE3cwzVY1x3WPk1AuDrDe2nLgi8STpHPUa4=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a> | <a href="%{compare_url}">Change view</a>)'
    format: html
