language: erlang
services:
  - redis-server
before_install:
  - ./rebar --config public.rebar.config get-deps compile
script:
  - rebar get-deps compile --config test.rebar.config ; INSTANCE_NAME=`hostname` LOGPLEX_CONFIG_REDIS_URL='redis://localhost:6379' LOGPLEX_SHARD_URLS='redis://localhost:6379' LOGPLEX_REDGRID_REDIS_URL='redis://localhost:6379' LOCAL_IP='127.0.0.1' LOGPLEX_COOKIE=123 ERL_LIBS=`pwd`/deps/:$ERL_LIBS ct_run -spec logplex.spec -pa ebin
otp_release:
  - R16B02
notifications:
  email: false
  hipchat:
    rooms:
      secure: "erv0U4jmmOP71ym5eNoya7SQffBkswE3Thcd8wWeOZ0SvfyOBQ57whLuugRky6++vAI8hDEl4N3LWkKLePm15KeViXCeX9+AZ7UexquOpR0NZl2vFjg/psu4E2fMQwcnbzS22hVXlVjSD5Ne+MGR/BDgEpIqiD3t7g325+Eahzs="
    template:
    - ! '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a> | <a href="%{compare_url}">Change view</a>)'
    format: html
