dist: trusty
language: erlang

otp_release:
  - R16B03-1

before_install:
  - .travis/install_compose.sh

before_script:
  - docker pull heroku/cedar:14
  - docker pull voidlock/erlang:R16B03-1-onbuild
  - docker pull redis:2.6

script:
  - docker-compose build
  - docker-compose run test

notifications:
  email: false
  hipchat:
    rooms:
      secure: C4Y4ZPATPESbHX34KCtpzfaVKTeUdSmGAk6qQuzDNtoiqqF8UeIXVOV30MKaLXLdWRBNNv57AnKAjX/uwSlNzcrjGkOsmC8SrSU9qTvxZz2VCkLdldQPOrrxumOKzOOCMb7mCa6OvsvYa1nKGoARDoqPGNd+1PK+N9W/+cYQaMw=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a> | <a href="%{compare_url}">Change view</a>)'
    format: html
