language: erlang
services:
- redis-server
before_install:
- "./rebar --config public.rebar.config get-deps compile"
script:
- rebar get-deps compile --config test.rebar.config ; INSTANCE_NAME=`hostname` LOGPLEX_CONFIG_REDIS_URL='redis://localhost:6379'
  LOGPLEX_SHARD_URLS='redis://localhost:6379' LOGPLEX_REDGRID_REDIS_URL='redis://localhost:6379'
  LOCAL_IP='127.0.0.1' LOGPLEX_COOKIE=123 ERL_LIBS=`pwd`/deps/:$ERL_LIBS ct_run -spec
  logplex.spec -pa ebin
otp_release:
  - 17.4
  - R16B02
notifications:
  email: false
  hipchat:
    rooms:
      secure: C4Y4ZPATPESbHX34KCtpzfaVKTeUdSmGAk6qQuzDNtoiqqF8UeIXVOV30MKaLXLdWRBNNv57AnKAjX/uwSlNzcrjGkOsmC8SrSU9qTvxZz2VCkLdldQPOrrxumOKzOOCMb7mCa6OvsvYa1nKGoARDoqPGNd+1PK+N9W/+cYQaMw=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a> | <a href="%{compare_url}">Change view</a>)'
    format: html
