data:
  image: redis:2.6
  command: true
db:
  image: redis:2.6
  command: redis-server
  volumes_from:
    - data
logplex:
  build: .
  command: ./bin/fig_logplex
  volumes:
    - .:/usr/src/app
  ports:
    - "8001:8001"
    - "8601:8601"
    - "6001:6001"
  links:
    - db
test:
  image: logplex_logplex
  # command: ./rebar get-deps compile --config test.rebar.config && ct_run -spec logplex.spec -pa ebin
  command: bash
  volumes:
    - .:/usr/src/app
  links:
    - db

